### ISSUE TITLE
⚠️ Post Kinds as Another Possible Addition

### ISSUE THREAD

**Issue by mrkrndvs** [cogdog/wp-posts2csv#2]
I wonder about the addition of ‘[Post Kinds](https://github.com/dshanske/indieweb-post-kinds)‘ to the information downloaded. As this is probably a little niche, might be more of a fork.

(Originally published at: https://collect.readwriterespond.com/post-kinds-as-another-possible-addition/)

**Comment by cogdog** [comment]
That is rather specialized but then again I have some Feed WordPress features included. 

What about this? I’d guess Post Kinds are stored in custom fields / post meta. What if there was an option to add the name of a post meta to be included as an extra column?

**Comment by mrkrndvs** [comment]
I think that would be a good approach.

**Comment by cogdog** [comment]
Now added to the current version (0.3). There is a field to enter comma separated post meta field names:

![post-meta-items](https://user-images.githubusercontent.com/463038/45367335-3c8af500-b59e-11e8-9c9b-111359d9364c.jpg)

On output, the values, if found, appear in the columns at the end

![extra](https://user-images.githubusercontent.com/463038/45367355-4dd40180-b59e-11e8-8617-8b1e27ea43bc.jpg)
